### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by tcjinaz** [Pridetronics/BaseBot#1]
Set VSCode up to format on save. There are some uglies lying around.

**Comment by tcjinaz** [comment]
Consider tying a command to a button to switch between arcade and tank drive. Implementation details are left to you

**Comment by tcjinaz** [comment]
Add a README.md

**Comment by AluminumChassis2** [comment]
The button to switch between the two drives is planned for the next development, I'll add a readme now.
